In [1]:

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

In [2]:
df_tourism = pd.read_csv('tourism_dataset_5000.csv')
df_sites = pd.read_csv('whc-sites-2021.csv')

In [3]:
df_tourism.head()

,Tourist ID,Age,Interests,Preferred Tour Duration,Accessibility,Site Name,Sites Visited,Tour Duration,Route ID,Tourist Rating,System Response Time,Recommendation Accuracy,VR Experience Quality,Satisfaction
0,1,48,"['Architecture', 'Art', 'History']",5,False,Eiffel Tower,"['Eiffel Tower', 'Great Wall of China', 'Taj M...",7,1000,1.6,3.73,97,4.5,3
1,2,37,"['Cultural', 'Nature']",6,False,Colosseum,['Great Wall of China'],1,2000,2.6,2.89,90,4.5,3
2,3,43,"['History', 'Art', 'Architecture']",6,True,Machu Picchu,['Eiffel Tower'],2,3000,1.7,2.22,94,4.7,3
3,4,46,"['Cultural', 'Art', 'Architecture']",8,False,Colosseum,"['Machu Picchu', 'Taj Mahal']",5,4000,2.0,2.34,92,4.7,3
4,5,53,"['Architecture', 'Art']",5,True,Colosseum,"['Machu Picchu', 'Taj Mahal', 'Great Wall of C...",7,5000,3.7,2.00,96,4.8,4

In [4]:
df_sites.head()

,Name,short_description,date_inscribed,danger,date_end,longitude,latitude,area_hectares,category_long,category_short,Country name,Region,iso_code,transboundary,rev_bis
0,L’Anse aux Meadows National Historic Site,<p>At the tip of the Great Northern Peninsula ...,1978,0,NaN,-55.616667,51.466667,7991.00,Cultural,C,Canada,Europe and North America,ca,0,NaN
1,Nahanni National Park,"<p>Located along the South Nahanni River, one ...",1978,0,NaN,-125.589444,61.547222,476560.00,Natural,N,Canada,Europe and North America,ca,0,NaN
2,Galápagos Islands,"<p>Situated in the Pacific Ocean some 1,000 km...",1978,0,2010.0,-90.501319,-0.689860,14066514.00,Natural,N,Ecuador,Latin America and the Caribbean,ec,0,Bis
3,City of Quito,"<p>Quito, the capital of Ecuador, was founded ...",1978,0,NaN,-78.512083,-0.220000,70.43,Cultural,C,Ecuador,Latin America and the Caribbean,ec,0,NaN
4,Simien National Park,<p>Massive erosion over the years on the Ethio...,1978,0,2017.0,38.066667,13.183333,13600.00,Natural,N,Ethiopia,Africa,et,0,NaN